// Code generated by ogen, DO NOT EDIT.
package openapi

type GetVideoRes interface {
	getVideoRes()
}

type ListVideosRes interface {
	listVideosRes()
}

type ReadyzRes interface {
	readyzRes()
}

type RecordVideoViewRes interface {
	recordVideoViewRes()
}
