// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetVideo implements getVideo operation.
	//
	// Get one video.
	//
	// GET /api/v1/videos/{id}
	GetVideo(ctx context.Context, params GetVideoParams) (GetVideoRes, error)
	// Healthz implements healthz operation.
	//
	// Liveness check.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzOK, error)
	// ListVideos implements listVideos operation.
	//
	// List available videos.
	//
	// GET /api/v1/videos
	ListVideos(ctx context.Context) (ListVideosRes, error)
	// Readyz implements readyz operation.
	//
	// Readiness check.
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// RecordVideoView implements recordVideoView operation.
	//
	// Record one idempotent video view.
	//
	// POST /api/v1/videos/{id}/views
	RecordVideoView(ctx context.Context, req *RecordViewRequest, params RecordVideoViewParams) (RecordVideoViewRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
