// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetVideoOperation        OperationName = "GetVideo"
	HealthzOperation         OperationName = "Healthz"
	ListVideosOperation      OperationName = "ListVideos"
	ReadyzOperation          OperationName = "Readyz"
	RecordVideoViewOperation OperationName = "RecordVideoView"
)
