// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideo = `-- name: GetVideo :one
SELECT id, title, m3u8_url, views_count, created_at, updated_at
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.M3u8Url,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVideoViews = `-- name: IncrementVideoViews :one
UPDATE videos
SET views_count = views_count + 1,
    updated_at = now()
WHERE id = $1
RETURNING views_count
`

func (q *Queries) IncrementVideoViews(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, incrementVideoViews, id)
	var views_count int64
	err := row.Scan(&views_count)
	return views_count, err
}

const insertViewEvent = `-- name: InsertViewEvent :execrows
INSERT INTO video_view_events (id, video_id, view_session_id, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (video_id, view_session_id) DO NOTHING
`

type InsertViewEventParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	VideoID       pgtype.UUID `db:"video_id" json:"video_id"`
	ViewSessionID string      `db:"view_session_id" json:"view_session_id"`
}

func (q *Queries) InsertViewEvent(ctx context.Context, arg InsertViewEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertViewEvent, arg.ID, arg.VideoID, arg.ViewSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, m3u8_url, views_count, created_at, updated_at
FROM videos
ORDER BY created_at DESC, title ASC
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.M3u8Url,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
